#!/bin/bash
HAVE_VAGRANT=$(which vagrant)
if [[ "$HAVE_VAGRANT" == "" ]]; then
    # we are running inside the Vagrant VM
    set -ex
    cd /vagrant/micropython
    make -C mpy-cross
    make -C ports/unix
    make -C ports/esp8266
else
    # we are running outside the Vagrant VM
    # run the same command in the VM
    vagrant ssh -c "build"
fi
