#!/bin/bash
HAVE_VAGRANT=$(which vagrant)
if [[ "$HAVE_VAGRANT" == "" ]]; then
    # we are running inside the Vagrant VM
    set -ex
    cd /vagrant
    git clone https://github.com/micropython/micropython
    cd micropython
    git submodule update --init
else
    # we are running outside the Vagrant VM
    # run the same command in the VM
    vagrant ssh -c "clone"
fi
